### ISSUE TITLE
Spawn Bug

### ISSUE THREAD

**Issue by cesarmr-github** [esx-framework/esx_garage#19]
I have a problem, when I spawn a personal vehicle, it comes out with an npc's license plate and not its own. It doesn't always happen to me but maybe 1 in 3 comes out with an npc's license plate. Then it can't be saved.

**Comment by Mycroft-Studios** [comment]
Which ESX Version?

**Comment by cesarmr-github** [comment]
latest

**Comment by Mycroft-Studios** [comment]
being?

**Comment by cesarmr-github** [comment]
Although it also happened to me before updating

**Comment by cesarmr-github** [comment]
What do you mean by "being"? I'm Spanish.

**Comment by Mycroft-Studios** [comment]
which ESX version are you using.

**Comment by cesarmr-github** [comment]
The latest version. Both of esx_core and garage. 1.11.2

**Comment by cesarmr-github** [comment]
I have tried manually applying the license plate and it still didn't work. I don't know what it is.

**Comment by cesarmr-github** [comment]
I noticed that if the car leaves with an NPC license plate, you go very far away, and come back. The car leaves and the license plate, colors, etc. are changed.

**Comment by Mycroft-Studios** [comment]
Fixed in next update

**Comment by Tacman1981** [comment]
no its still not fixed. unless your update is still in the works. it still happens but its rare now

**Comment by cesarmr-github** [comment]
I think it still happens.
